[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"
  # Ensure dev dependencies are installed
  NPM_FLAGS = "--production=false"
  # Only include essential environment variables
  # REACT_APP_SUPABASE_URL and REACT_APP_SUPABASE_ANON_KEY should be set in Netlify UI

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 