[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  # Prevent treating warnings as errors
  CI = "false"
  # Set correct NODE_ENV for production builds
  NODE_ENV = "production"
  # Note: Actual Supabase credentials should be set in Netlify UI, not here

# This will still work alongside the _redirects file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 