[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  # Prevent treating warnings as errors
  CI = "false"
  # Ensure development dependencies are installed
  NODE_ENV = "development"
  # Disable secrets scanning for the Supabase anon key (public API key)
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_SUPABASE_ANON_KEY"
  # REACT_APP_SUPABASE_URL and REACT_APP_SUPABASE_ANON_KEY should be set in Netlify UI

# This will still work alongside the _redirects file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 