[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  # Prevent treating warnings as errors
  CI = "false"
  # Ensure development dependencies are installed
  NODE_ENV = "development"
  # Tell Netlify to ignore the Supabase key during secrets scanning
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_SUPABASE_ANON_KEY"
  # Note: Actual Supabase credentials should be set in Netlify UI, not here

# This will still work alongside the _redirects file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 