[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  # Prevent treating warnings as errors
  CI = "false"
  # Ensure correct NODE_ENV
  NODE_ENV = "production"
  # REACT_APP_SUPABASE_URL and REACT_APP_SUPABASE_ANON_KEY should be set in Netlify UI

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 