[build]
  command = "npm install --include=dev && npm run build:netlify"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  # Prevent treating warnings as errors
  CI = "false"
  # Set correct NODE_ENV for production builds
  NODE_ENV = "production"
  # Tell Netlify to ignore the Supabase key during secrets scanning
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_SUPABASE_ANON_KEY"
  # Note: Actual Supabase credentials should be set in Netlify UI, not here

# This will still work alongside the _redirects file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Improve performance with compression and caching headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.woff*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 